name: Build Kernel

on:
  workflow_dispatch:
  
jobs:
  build_recovery:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [A546E, A546B]
        
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install repo
        run: |
          mkdir ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo -o ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: Set UP Build Environment
        run: |
          sudo apt update
          sudo apt -y upgrade
          sudo apt -y install build-essential gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses5

          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Clean Dir
        run: |
          echo ~
          ls | xargs rm -fr

      - name: Prepare extra files
        run: |
          mkdir twrp-build
          curl https://vaz15k.github.io/bug-free-couscous/Tools/magiskboot -o ~/bin/magiskboot
          chmod a+x ~/magiskboot
          sudo ln -sf ~/bin/magiskboot /usr/bin/magiskboot
          
          if [ "${{ matrix.target }}" == "A546B" ]; then
            wget -c https://vaz15k.github.io/bug-free-couscous/Imagens/A546B/recovery.img -O twrp-build/recovery-A546B.img
          elif [ "${{ matrix.target }}" == "A546E" ]; then
            wget -c https://vaz15k.github.io/bug-free-couscous/Imagens/A546E/recovery.img -O twrp-build/recovery-A546E.img
          fi
          
      - name: Initialize repo
        run: |
          mkdir twrp-12.1
          cd twrp-12.1
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1

      - name: Repo Sync
        run: |
          repo sync -j$(nproc --all) --force-sync

      - name: Cloning Trees
        run: |
          git clone --branch twrp-12.1 https://github.com/Vaz15k/android_device_samsung_a54x.git device/samsung/a54x

      - name: Build Recovery
        run: |
          export ALLOW_MISSING_DEPENDENCIES=true
          . build/envsetup.sh
          lunch twrp_a54x-eng && mka recoveryimage -j$(nproc --all)

      - name: Repack Image
        run: |
          mkdir ~/files
          cp out/target/product/a54x/recovery.img ../twrp-build/twrp.img
          cd ../twrp-build
          magiskboot unpack twrp.img
          magiskboot repack recovery-${{ matrix.target }}.img recovery.img
          tar cf TWRP-${{ matrix.target }}_$(date +"%Y-%m-%d").tar recovery.img
          cp TWRP* ~/files

      - name: Publish to GitHub
        id: release
        uses: softprops/action-gh-release@v2
        with:
          files: ~/files/TWRP*
          name: TWRP / OFRP
          tag_name: ${{ format('{0:%Y-%m-%d}', github.event.created_at) }}
          body: |
            :rocket: *Built with love by GitHub Actions.*
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
